### ISSUE TITLE
Replace examples in readme with a table of contents to examples

### ISSUE THREAD

**Issue by desicochrane** [desicochrane/machine#8]
I think the readme would be best if it was simply an intro and getting started, then a list of links pointing to various examples. 

The whole point of this library is power from simplicity, and currently the readme does not reflect simplicity.

**Comment by kmjayadeep** [comment]
i will do this. How about creating an examples folder which contains README files of each example? In main README file We can provide a table with links to these individual files.

**Comment by rachitGulati** [comment]
I have created a PR please have a look :)
