### ISSUE TITLE
Add tests coverage badges to readme

### ISSUE THREAD

**Issue by desicochrane** [desicochrane/machine#9]
The repo would be more legitimate if it had coverage and quality badges!

**Comment by shmesa22** [comment]
I can work on this one

**Comment by shmesa22** [comment]
@desicochrane in order to complete this task I will need you to go to [coveralls](https://coveralls.io/) login with your GitHub account, turn on coveralls reports for this project and add the repo-token to `.coveralls.yml`

**Comment by desicochrane** [comment]
Thank you!
